export type Total = {
  name: {
    size: string
    whipGroup: string
    rawChocolateWhip: string
    coffeeCream: string
    milkGroup: string
    changeMilkGroup: string
    allMilk: string
    powderGroup: string
    sauceGroup: string
    chocoSaucePlus: string,
    caramelSaucePlus: string,
    syrupGroup: string
    changeSyrupGroup: string
    chipGroup: string
    wristletShot: string
    changeEspresso: string
    iceGroup: string
    hotGroup: string
    honeyPlus: string
    cocoa:string
    cinnamon:string
    teaLeaf: string
    vanillaPlus: string,
    caramelPlus: string,
    classicPlus: string,
    mochaPlus: string,
    whiteMochaPlus: string,
    chaiPlus: string,
    valenciaPlus: string,
    gingerPlus: string,
    whipPlus: string
    steamMilkPlus: string
    foamMilkPlus: string
    shotPlusGroup: string
    coffeeRoastPlusGroup: string
    chocolateChipPlus: string
    decaf: string
    mousseFoam: string
    citrusPulpPlusGroup: string
    teaLeafAddGroup: string
    teaLeafPlus: string
  }
  shop: {
    price: {
      size: number
      whipGroup: number
      rawChocolateWhip: number
      coffeeCream: number
      milkGroup: number
      changeMilkGroup: number
      allMilk: number
      powderGroup: number
      sauceGroup: number
      chocoSaucePlus: number,
      caramelSaucePlus: number,
      syrupGroup: number
      changeSyrupGroup: number
      chipGroup: number
      wristletShot: number
      changeEspresso: number
      iceGroup: number
      hotGroup: number
      honeyPlus: number
      cocoa:  number
      cinnamon: number
      teaLeaf: number
      vanillaPlus: number,
      caramelPlus: number,
      classicPlus: number,
      mochaPlus: number,
      whiteMochaPlus: number,
      chaiPlus: number,
      valenciaPlus: number,
      gingerPlus: number,
      whipPlus: number
      steamMilkPlus: number
      foamMilkPlus: number
      shotPlusGroup: number
      coffeeRoastPlusGroup: number
      chocolateChipPlus: number
      decaf: number
      mousseFoam: number
      citrusPulpPlusGroup: number
      teaLeafAddGroup: number
      teaLeafPlus: number
    }
    current: {
      size: string
      whipGroup: boolean
      rawChocolateWhip: boolean
      coffeeCream: boolean
      milkGroup: boolean
      changeMilkGroup: boolean
      allMilk: boolean
      powderGroup: boolean
      chocoSaucePlus: boolean,
      caramelSaucePlus: boolean,
      syrupGroup: boolean
      changeSyrupGroup: boolean
      chipGroup: boolean
      wristletShot: boolean
      changeEspresso: boolean
      iceGroup: boolean
      hotGroup: boolean
      honeyPlus: boolean
      cocoa:boolean
      cinnamon:boolean
      teaLeaf: boolean
      vanillaPlus: boolean,
      caramelPlus: boolean,
      classicPlus: boolean,
      mochaPlus: boolean,
      whiteMochaPlus: boolean,
      chaiPlus: boolean,
      valenciaPlus: boolean,
      gingerPlus: boolean,
      whipPlus: boolean
      steamMilkPlus: boolean
      foamMilkPlus: boolean
      shotPlusGroup: boolean
      coffeeRoastPlusGroup: boolean
      chocolateChipPlus: boolean
      decaf: boolean
      mousseFoam: boolean
      citrusPulpPlusGroup: boolean
      teaLeafAddGroup: boolean
      teaLeafPlus: boolean
    }
  }
  takeout: {
    price: {
      size: number
      whipGroup: number
      rawChocolateWhip: number
      coffeeCream: number
      milkGroup: number
      changeMilkGroup: number
      allMilk: number
      powderGroup: number
      sauceGroup: number
      chocoSaucePlus: number,
      caramelSaucePlus: number,
      syrupGroup: number
      changeSyrupGroup: number
      chipGroup: number
      wristletShot: number
      changeEspresso: number
      iceGroup: number
      hotGroup: number
      honeyPlus: number
      cocoa:  number
      cinnamon: number
      teaLeaf: number
      vanillaPlus: number,
      caramelPlus: number,
      classicPlus: number,
      mochaPlus: number,
      whiteMochaPlus: number,
      chaiPlus: number,
      valenciaPlus: number,
      gingerPlus: number,
      whipPlus: number
      steamMilkPlus: number
      foamMilkPlus: number
      shotPlusGroup: number
      coffeeRoastPlusGroup: number
      chocolateChipPlus: number
      decaf: number
      mousseFoam: number
      citrusPulpPlusGroup: number
      teaLeafAddGroup: number
      teaLeafPlus: number
    }
    current: {
      size: string
      whipGroup: boolean
      rawChocolateWhip: boolean
      coffeeCream: boolean
      milkGroup: boolean
      changeMilkGroup: boolean
      allMilk: boolean
      powderGroup: boolean
      sauceGroup: boolean
      chocoSaucePlus: boolean,
      caramelSaucePlus: boolean,
      syrupGroup: boolean
      changeSyrupGroup: boolean
      chipGroup: boolean
      wristletShot: boolean
      changeEspresso: boolean
      iceGroup: boolean
      hotGroup: boolean
      honeyPlus: boolean
      cocoa:  boolean
      cinnamon: boolean
      teaLeaf: boolean
      vanillaPlus: boolean,
      caramelPlus: boolean,
      classicPlus: boolean,
      mochaPlus: boolean,
      whiteMochaPlus: boolean,
      chaiPlus: boolean,
      valenciaPlus: boolean,
      gingerPlus: boolean,
      whipPlus: boolean
      steamMilkPlus: boolean
      foamMilkPlus: boolean
      shotPlusGroup: boolean
      coffeeRoastPlusGroup: boolean
      chocolateChipPlus: boolean
      decaf: boolean
      mousseFoam: boolean
      citrusPulpPlusGroup: boolean
      teaLeafAddGroup: boolean
      teaLeafPlus: boolean
    }
  }
}
